<?php

if (function_exists('acf_add_local_field_group')):

  acf_add_local_field_group(array(
    'key' => 'group_6278db75521bd',
    'title' => 'Form',
    'fields' => array(
      array(
        'key' => 'field_62790645a9405',
        'label' => 'Fields',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_62793ff0ebea5',
        'label' => 'Form Fields',
        'name' => 'form_fields',
        'aria-label' => '',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'tpf-collapse',
          'id' => '',
        ),
        'layouts' => array(
          'layout_62793ffb28177' => array(
            'key' => 'layout_62793ffb28177',
            'name' => 'text',
            'label' => 'Text',
            'display' => 'row',
            'sub_fields' => array(
              array(
                'key' => 'field_627946bd57de2',
                'label' => 'Label',
                'name' => 'label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_633c14815806c',
                'label' => 'Name',
                'name' => 'name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_628d10d3d5d91',
                'label' => 'Placeholder',
                'name' => 'placeholder',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794001ebea6',
                'label' => 'Width',
                'name' => 'width',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  '1-1' => '100%',
                  '2-3' => '70%',
                  '3-5' => '60%',
                  '1-2' => '50%',
                  '2-5' => '40%',
                  '1-3' => '30%',
                  '1-4' => '25%',
                  '1-5' => '20%',
                  'expand' => 'Expand',
                ),
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => 'field_627946a757de1',
                'label' => 'Required',
                'name' => 'required',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_62794b11699dc',
                'label' => 'Show Description',
                'name' => 'show_description',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_627946cf57de4',
                'label' => 'Description',
                'name' => 'description',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_62794b11699dc',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'br',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_62794bfd6d4d8' => array(
            'key' => 'layout_62794bfd6d4d8',
            'name' => 'email',
            'label' => 'Email',
            'display' => 'row',
            'sub_fields' => array(
              array(
                'key' => 'field_62794bfd6d4d9',
                'label' => 'Label',
                'name' => 'label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794bfd6d4da',
                'label' => 'Name',
                'name' => 'name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_628d11939acf3',
                'label' => 'Placeholder',
                'name' => 'placeholder',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794bfd6d4db',
                'label' => 'Width',
                'name' => 'width',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  '1-1' => '100%',
                  '2-3' => '70%',
                  '3-5' => '60%',
                  '1-2' => '50%',
                  '2-5' => '40%',
                  '1-3' => '30%',
                  '1-4' => '25%',
                  '1-5' => '20%',
                  'expand' => 'Expand',
                ),
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => 'field_62794bfd6d4dc',
                'label' => 'Required',
                'name' => 'required',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_62794bfd6d4dd',
                'label' => 'Show Description',
                'name' => 'show_description',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_62794bfd6d4de',
                'label' => 'Description',
                'name' => 'description',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_62794bfd6d4dd',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'br',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_62794c2a925f9' => array(
            'key' => 'layout_62794c2a925f9',
            'name' => 'textarea',
            'label' => 'Textarea',
            'display' => 'row',
            'sub_fields' => array(
              array(
                'key' => 'field_62794c2a925fa',
                'label' => 'Label',
                'name' => 'label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794c2a925fb',
                'label' => 'Name',
                'name' => 'name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_628d128bbc611',
                'label' => 'Placeholder',
                'name' => 'placeholder',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794c2a925fc',
                'label' => 'Width',
                'name' => 'width',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  '1-1' => '100%',
                  '2-3' => '70%',
                  '3-5' => '60%',
                  '1-2' => '50%',
                  '2-5' => '40%',
                  '1-3' => '30%',
                  '1-4' => '25%',
                  '1-5' => '20%',
                  'expand' => 'Expand',
                ),
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => 'field_62794c5aff179',
                'label' => 'Rows',
                'name' => 'rows',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '20',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794c2a925fd',
                'label' => 'Required',
                'name' => 'required',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_62794c2a925fe',
                'label' => 'Show Description',
                'name' => 'show_description',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_62794c2a925ff',
                'label' => 'Description',
                'name' => 'description',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_62794c2a925fe',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_62794ccecadd7' => array(
            'key' => 'layout_62794ccecadd7',
            'name' => 'select',
            'label' => 'Select',
            'display' => 'row',
            'sub_fields' => array(
              array(
                'key' => 'field_62794ccfcadd8',
                'label' => 'Label',
                'name' => 'label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794ccfcadd9',
                'label' => 'Name',
                'name' => 'name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794d6d67a89',
                'label' => 'Placeholder',
                'name' => 'placeholder',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '- Select -',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794ccfcadda',
                'label' => 'Width',
                'name' => 'width',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  '1-1' => '100%',
                  '2-3' => '70%',
                  '3-5' => '60%',
                  '1-2' => '50%',
                  '2-5' => '40%',
                  '1-3' => '30%',
                  '1-4' => '25%',
                  '1-5' => '20%',
                  'expand' => 'Expand',
                ),
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => 'field_62794ccfcaddb',
                'label' => 'Required',
                'name' => 'required',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_62794ccfcaddc',
                'label' => 'Show Description',
                'name' => 'show_description',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_62794cd9cadde',
                'label' => 'Options',
                'name' => 'options',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => 'One option per line as: value=Label eg: 1=Option 1',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => '',
              ),
              array(
                'key' => 'field_62794ccfcaddd',
                'label' => 'Description',
                'name' => 'description',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_62794ccfcaddc',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'br',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_62794ca5c1b75' => array(
            'key' => 'layout_62794ca5c1b75',
            'name' => 'file',
            'label' => 'File',
            'display' => 'row',
            'sub_fields' => array(
              array(
                'key' => 'field_62794ca5c1b76',
                'label' => 'Label',
                'name' => 'label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794ca5c1b77',
                'label' => 'Name',
                'name' => 'name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_628d13bb53d4f',
                'label' => 'Placeholder',
                'name' => 'placeholder',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => 'Select File',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_62794ca5c1b78',
                'label' => 'Width',
                'name' => 'width',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  '1-1' => '100%',
                  '2-3' => '70%',
                  '3-5' => '60%',
                  '1-2' => '50%',
                  '2-5' => '40%',
                  '1-3' => '30%',
                  '1-4' => '25%',
                  '1-5' => '20%',
                  'expand' => 'Expand',
                ),
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => 'field_62794ca5c1b79',
                'label' => 'Required',
                'name' => 'required',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_62794ca5c1b7a',
                'label' => 'Show Description',
                'name' => 'show_description',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_62794ca5c1b7b',
                'label' => 'Description',
                'name' => 'description',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_62794ca5c1b7a',
                      'operator' => '==',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'br',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
        ),
        'min' => '',
        'max' => '',
        'button_label' => 'Add Field',
      ),
      array(
        'key' => 'field_627905dde41d3',
        'label' => 'Settings',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_6278db7997dc4',
        'label' => 'Action Url',
        'name' => 'action_url',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'Custom url to submit the form. Leave empty if you are not sure, default is "./"',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_628b9b0f188e6',
        'label' => 'Captcha',
        'name' => 'captcha',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Enable number captcha ( x + y ?) to prevent spam.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_627b67b89bffd',
        'label' => 'Labels & Placeholders',
        'name' => 'labels',
        'aria-label' => '',
        'type' => 'radio',
        'instructions' => 'Show form input fields labels',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          1 => 'Labels',
          2 => 'Placeholders',
          3 => 'Labels + Placeholders',
        ),
        'default_value' => 3,
        'return_format' => 'value',
        'allow_null' => 0,
        'other_choice' => 0,
        'layout' => 'horizontal',
        'save_other_choice' => 0,
      ),
      array(
        'key' => 'field_6364cf5f8c7e3',
        'label' => 'Grid Size',
        'name' => 'grid_size',
        'aria-label' => '',
        'type' => 'radio',
        'instructions' => 'Space between fields in a form.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'default' => 'Default',
          'small' => 'Small',
          'large' => 'Large',
        ),
        'default_value' => 'default',
        'return_format' => 'value',
        'allow_null' => 0,
        'other_choice' => 0,
        'layout' => 'horizontal',
        'save_other_choice' => 0,
      ),
      array(
        'key' => 'field_627909d55d91d',
        'label' => 'Success Title',
        'name' => 'success_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'Title that will be displayed on the modal window after successful form submission.
	Use {field_name} to reference a form field.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_6278dc1792a6f',
        'label' => 'Success Message',
        'name' => 'success_message',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'Message that will be shown to the user after successful submit. Use {field_name} to reference a form field.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 2,
        'new_lines' => '',
      ),
      array(
        'key' => 'field_6278df9596349',
        'label' => 'Submit Button Text',
        'name' => 'submit_button_text',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Submit',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_6364d0fb0f46a',
        'label' => 'Emails',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_62791117c4fe9',
        'label' => 'Send Email',
        'name' => 'send_email',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Receive email submissions from this form.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '100',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_6278fc99490b3',
        'label' => 'Subject',
        'name' => 'subject',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'Email subject when receiving submissions. Use {field_name} to reference a form field.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_62791117c4fe9',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_62791145c4fea',
        'label' => 'Admin Email',
        'name' => 'admin_email',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'Email address to receive submissions to. if empty, emails from site settings will be used. You can type multiple email addresses separated by comma.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_62791117c4fe9',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '100',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_6374c436551af',
        'label' => 'Email Body',
        'name' => 'email_body',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => 'Email content that will be sent to the admin.
	Use {field_name} to reference a form field. Eg: Hello {first_name}',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_62791117c4fe9',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'visual',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_6364d12cf583e',
        'label' => 'Posts',
        'name' => '',
        'aria-label' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_62790751f6c88',
        'label' => 'Create Post',
        'name' => 'create_post',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => 'Create a post from the form submition. Note that form field names needs to match post type fields.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '100',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_6278fb1f5494f',
        'label' => 'Post Type',
        'name' => 'select_post_type',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => 'Select custom post type',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_62790751f6c88',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'tpf_content_blocks' => 'tpf_content_blocks',
        ),
        'default_value' => false,
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_627a230d1e4b6',
        'label' => 'New Post Title',
        'name' => 'new_post_title',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => 'Use {field_name} to reference a form field.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_62790751f6c88',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_628b78e201d96',
        'label' => 'Allow Duplicated Posts',
        'name' => 'allow_duplicated_posts',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_62790751f6c88',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 1,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_628b7908f3478',
        'label' => 'Field name to validate',
        'name' => 'field_name_to_validate',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_628b78e201d96',
              'operator' => '!=',
              'value' => '1',
            ),
            array(
              'field' => 'field_62790751f6c88',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_628b82cf2f3dc',
        'label' => 'Duplicate Message',
        'name' => 'duplicate_message',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'You can use form fields like: {my_field}',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_628b78e201d96',
              'operator' => '!=',
              'value' => '1',
            ),
            array(
              'field' => 'field_62790751f6c88',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 3,
        'new_lines' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'project-forms',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'permalink',
      1 => 'the_content',
      2 => 'excerpt',
      3 => 'discussion',
      4 => 'comments',
      5 => 'revisions',
      6 => 'slug',
      7 => 'author',
      8 => 'format',
      9 => 'page_attributes',
      10 => 'featured_image',
      11 => 'categories',
      12 => 'tags',
      13 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'modified' => 1668598686,
  ));

endif;