<?php

if (!defined('ABSPATH')) {
  exit;
}

add_action('acf/include_fields', function () {
  if (!function_exists('acf_add_local_field_group')) {
    return;
  }

  acf_add_local_field_group(array(
    'key' => 'group_652d370dc457f',
    'title' => 'Search Filters',
    'fields' => array(
      array(
        'key' => 'field_652d6239033f1',
        'label' => 'Type',
        'name' => 'type',
        'aria-label' => '',
        'type' => 'radio',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '80',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'checkbox' => 'Checkbox',
          'radio' => 'Radio',
          'select' => 'Select',
        ),
        'default_value' => '',
        'return_format' => 'value',
        'allow_null' => 0,
        'other_choice' => 0,
        'layout' => 'horizontal',
        'save_other_choice' => 0,
      ),
      array(
        'key' => 'field_652d4c5159442',
        'label' => 'Sort',
        'name' => 'sort',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '20',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_652d47feefc0a',
        'label' => 'Category',
        'name' => 'category',
        'aria-label' => '',
        'type' => 'taxonomy',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'product_cat',
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'id',
        'field_type' => 'multi_select',
        'allow_null' => 1,
        'bidirectional' => 0,
        'multiple' => 0,
        'bidirectional_target' => array(),
      ),
      array(
        'key' => 'field_652d3def6c8c5',
        'label' => 'Items',
        'name' => 'items',
        'aria-label' => '',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'tpf-collapse',
          'id' => '',
        ),
        'layouts' => array(
          'layout_652d41771cd68' => array(
            'key' => 'layout_652d41771cd68',
            'name' => 'on_sale',
            'label' => 'On Sale',
            'display' => 'row',
            'sub_fields' => array(
              array(
                'key' => 'field_652d419b6c8c6',
                'label' => 'Label',
                'name' => 'label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          /*
          'layout_652d41e0644cb' => array(
            'key' => 'layout_652d41e0644cb',
            'name' => 'with_rating',
            'label' => 'With Rating',
            'display' => 'row',
            'sub_fields' => array(
              array(
                'key' => 'field_652d41f3644cd',
                'label' => 'Label',
                'name' => 'label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          */
          'layout_652d420adf66e' => array(
            'key' => 'layout_652d420adf66e',
            'name' => 'by_price',
            'label' => 'By Price',
            'display' => 'row',
            'sub_fields' => array(
              array(
                'key' => 'field_652d421edf670',
                'label' => 'Label',
                'name' => 'label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_652d423cdf672',
                'label' => 'Min',
                'name' => 'min',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_652d426adf673',
                'label' => 'Max',
                'name' => 'max',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          'layout_652d427d71707' => array(
            'key' => 'layout_652d427d71707',
            'name' => 'by_meta',
            'label' => 'By Meta',
            'display' => 'row',
            'sub_fields' => array(
              array(
                'key' => 'field_652d428371709',
                'label' => 'Label',
                'name' => 'label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_652d42907170b',
                'label' => 'Key',
                'name' => 'key',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Name of the field to search for',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_652d42c5c0788',
                'label' => 'Value',
                'name' => 'value',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Value of the field to search for',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
        ),
        'min' => '',
        'max' => '',
        'button_label' => 'Add Row',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'project-filters',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  ));
});
